# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        MainWindow.setStyleSheet("background-color: rgb(90, 90, 90);\n"
"font: 9pt \"Arial\";\n"
"color: rgb(223, 223, 223);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.default_1 = QtWidgets.QPushButton(self.centralwidget)
        self.default_1.setGeometry(QtCore.QRect(40, 240, 191, 121))
        self.default_1.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(80, 80, 80);\n"
"    color:  rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(75, 75, 75);\n"
"}")
        self.default_1.setObjectName("default_1")
        self.prog_args = QtWidgets.QComboBox(self.centralwidget)
        self.prog_args.setGeometry(QtCore.QRect(580, 130, 290, 30))
        self.prog_args.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(80, 80, 80);\n"
"    color:  rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(75, 75, 75);\n"
"}")
        self.prog_args.setObjectName("prog_args")
        self.prog_args.addItem("")
        self.prog_args.addItem("")
        self.prog_args.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 30, 250, 50))
        self.label.setStyleSheet("font: 15pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.docs = QtWidgets.QPushButton(self.centralwidget)
        self.docs.setGeometry(QtCore.QRect(310, 280, 230, 130))
        self.docs.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(70, 70, 70);\n"
"    color:  rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(65, 65, 65);\n"
"}")
        self.docs.setObjectName("docs")
        self.gaming = QtWidgets.QPushButton(self.centralwidget)
        self.gaming.setGeometry(QtCore.QRect(310, 440, 230, 130))
        self.gaming.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(70, 70, 70);\n"
"    color:  rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(65, 65, 65);\n"
"}")
        self.gaming.setObjectName("gaming")
        self.programming = QtWidgets.QPushButton(self.centralwidget)
        self.programming.setGeometry(QtCore.QRect(310, 120, 230, 130))
        self.programming.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(70, 70, 70);\n"
"    color:  rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(65, 65, 65);\n"
"}")
        self.programming.setObjectName("programming")
        self.docs_argd = QtWidgets.QComboBox(self.centralwidget)
        self.docs_argd.setGeometry(QtCore.QRect(580, 290, 290, 30))
        self.docs_argd.setStyleSheet("QPushButton {\n"
"    border-radius:  10px;\n"
"    background-color: rgb(80, 80, 80);\n"
"    color:  rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  rgb(75, 75, 75);\n"
"}")
        self.docs_argd.setObjectName("docs_argd")
        self.docs_argd.addItem("")
        self.docs_argd.addItem("")
        self.docs_argd.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.default_1.setText(_translate("MainWindow", "Режим по умолчанию"))
        self.prog_args.setItemText(0, _translate("MainWindow", "Проект 1"))
        self.prog_args.setItemText(1, _translate("MainWindow", "Проект 2"))
        self.prog_args.setItemText(2, _translate("MainWindow", "Проект 3"))
        self.label.setText(_translate("MainWindow", "Выберите сценарий"))
        self.docs.setText(_translate("MainWindow", "Работа с документами"))
        self.gaming.setText(_translate("MainWindow", "Играть"))
        self.programming.setText(_translate("MainWindow", "Программирование"))
        self.docs_argd.setItemText(0, _translate("MainWindow", "Файл 1"))
        self.docs_argd.setItemText(1, _translate("MainWindow", "Файл 2"))
        self.docs_argd.setItemText(2, _translate("MainWindow", "Файл 3"))
